; PlatformIO Project Configuration File
;
; Internet Radio based on ESP32

[platformio]
description = Internet Radio and Clock based on ESP32
default_envs = internet-radio

[env:internet-radio]
platform = espressif32
board = esp-wrover-kit
framework = arduino
build_flags =
	-Os
	-DCORE_DEBUG_LEVEL=0
	; Enable PSRAM support for ESP32-WROVER, used for the audio streaming buffer.
	; -DBOARD_HAS_PSRAM
	; -mfix-esp32-psram-cache-issue
build_unflags = -O2
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB

; MacOS
upload_port = /dev/cu.usbserial*
monitor_port = /dev/cu.usbserial*

; Linux
; upload_port = /dev/ttyUSB*
; monitor_port = /dev/ttyUSB*

monitor_speed = 115200
lib_deps =
	paulstoffregen/Time@^1.6.1
	bblanchon/ArduinoJson@5.13.4
	esp32async/ESPAsyncWebServer@^3.6.1
	adafruit/Adafruit GFX Library@^1.11.3
	adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit BusIO@^1.13.2
	adafruit/Adafruit SH110X@^2.1.8
	earlephilhower/ESP8266Audio@2.2.0